all:
  children:
    dev:
      hosts:
        local-dev:
          ansible_connection: local

        ubuntu-devops:
          ansible_host: 35.197.237.184
          ansible_user: lawaloladelesulaiman
